name: JS Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install ESLint globally
        run: npm install -g eslint

      - name: Run ESLint on all JS files
        run: eslint '**/*.js' || exit 1
